##aljabar matrik
 - berikan penjellasan apa itu matrik
 - operasi matrik PENJUMLAHAN PERKALIAN tranpose
 - buat program untuk mengalihkah matrik a dan b m x n matriks a,n x k matriks b

saya di suruh membuat maatriks

Secara sederhana, matriks adalah kumpulan angka yang disusun dalam bentuk tabel yang terdiri dari baris dan kolom. Dalam konteks yang lebih luas, matriks dapat digunakan untuk merepresentasikan data, memecahkan sistem persamaan linear, menunjukkan hubungan linier antara variabel, dan bahkan dalam analisis grafik. Ini adalah konsep yang sangat penting dalam matematika dan memiliki banyak aplikasi di berbagai bidang, mulai dari ilmu komputer hingga ilmu sosial.


### Struktur Matriks
Matriks terdiri dari elemen-elemen yang ditempatkan dalam baris dan kolom. Sebuah matriks 3x2 memiliki 3 baris dan 2 kolom, sebagai contoh. Setiap elemen matriks diberi indeks dengan notasi i,j, di mana i menunjukkan baris dan j menunjukkan kolom, seperti yang ditunjukkan oleh elemen di baris ke-2 dan kolom ke-1. Indeks 2,1 diberikan kepada elemen di baris ke-2 dan kolom ke-1.



### Notasi Matriks
Matriks sering ditunjukkan dengan huruf kapital, seperti A, B, atau C. Untuk membedakan dimensinya, matriks dapat ditambahkan subskrip yang menunjukkan jumlah baris dan kolom. Misalnya, matriks A dapat ditulis sebagai A[m x n], di mana m adalah jumlah baris dan n adalah jumlah kolom.

### Operasi Matriks
1. Penjumlahan dan Pengurangan Matriks: Dilakukan antara matriks dengan dimensi yang sama, yaitu jumlah baris dan kolom yang identik.
2. Perkalian Matriks: Dilakukan antara matriks yang memenuhi aturan perkalian matriks, yaitu jumlah baris dan kolom kedua matriks harus sama.
3. Inverse Matriks: Digunakan untuk membalikkan efek perkalian matriks.
4. Determinan Matriks: Dilakukan antara matriks yang memenuhi aturan perkalian matriks, yaitu jumlah baris dan kolom kedu
5. Transpos matriks: proses mengubah baris matriks menjadi kolom atau sebaliknya.


### Aplikasi Matriks
1. Penjumlahan dan Pengurangan Matriks: Dilakukan antara matriks dengan dimensi yang sama, yaitu jumlah baris dan kolom yang identik.
2. Perkalian Matriks: Dilakukan antara matriks yang memenuhi aturan perkalian matriks, yaitu jumlah baris dan kolom kedua matriks harus sama.
3. Inverse Matriks: Digunakan untuk membalikkan efek perkalian matriks.
4. Determinan Matriks: Dilakukan antara matriks yang memenuhi aturan perkalian matriks, yaitu jumlah baris dan kolom kedu
5. Transpos matriks: proses mengubah baris matriks menjadi kolom atau sebaliknya.

In [ ]:
#membuat struktur matriks
import numpy as np
import sympy as sy

#operasi penjumlahan matrik
a=np.array([[3,1],[8,10],[1,3]])
#mendefinisikan matfrik a
b=np.array([[1,7],[2,5],[4,1]])
#mendefinisikan matrik b
def tambah_matriks(matriks1, matriks2):
    # Pastikan kedua matriks memiliki ukuran yang sama
    if len(matriks1) != len(matriks2) or len(matriks1[0]) != len(matriks2[0]):
        return "Ukuran matriks tidak sesuai"

    # Inisialisasi matriks hasil dengan ukuran yang sama
    hasil = []
    for i in range(len(matriks1)):
        baris_hasil = []
        for j in range(len(matriks1[0])):
            baris_hasil.append(matriks1[i][j] + matriks2[i][j])
        hasil.append(baris_hasil)

    return hasil


hasil = tambah_matriks(a, b)
for baris in hasil:
    print(baris)


[4, 8]
[10, 15]
[5, 4]


Salah satu operasi matriks yang pertama kita bahas adalah penjumlahan matriks, yang merupakan penjumlahan dua matriks dengan letak komponen yang sama. Sebenarnya, ada syarat bahwa matriks dapat dijumlahkan.

Apa syarat matriks yang dapat dijumlahkan? Matriks tidak dapat dijumlahkan jika dua matriks tidak memiliki ordo yang sama. Matriks berikut adalah contohnya.

\begin{align*}
A+B&=
\begin{bmatrix}
3&1\\
8&10\\
1&3
\end{bmatrix}
+
\begin{bmatrix}
1&7\\
2&5\\
4&1
\end{bmatrix}\\
&=
\begin{bmatrix}
3+1&1+7\\
8+2&10+5\\
1+4&3+1\\
\end{bmatrix}
=\begin{bmatrix}
4&8\\
10&15\\
5&4
\end{bmatrix}
\end{align*}



In [ ]:
#membuat struktur matriks
import numpy as np
import sympy as sy

#mendefinisikan matrik a
a=np.array([[3,7,1],[8,1,10],[1,3,7]])
#mendefinisikan matfrik b
b=np.array([[1,7,8],[2,1,5],[2,4,1]])
#operasi perkalian matrik

# Inisialisasi matriks hasil perkalian dengan ukuran yang sesuai
hasil =np.array([[0,0,0],[0,0,0],[0,0,0]])
# Melakukan perkalian matriks
for i in range(len(a)):
    for j in range(len(b[0])):
        for k in range(len(b)):
            hasil[i][j] += a[i][k] * b[k][j]

# Tampilkan hasil
for baris in hasil:
    print(baris)

[19 32 60]
[30 97 79]
[21 38 30]


Perkalian Matriks 3x3: Perkalian dua matriks berukuran 3x3 akan menghasilkan matriks baru berukuran 3x3. Cara melakukannya adalah sebagai berikut.

Perkalian matriks 3 kali 3.

  1. Pertama, kalikan baris pertama matriks A dengan kolom pertama matriks B. Anggota bilangan pada baris pertama dan kolom pertama hasil perkalian akan dihasilkan.
  
  2. Matriks B's kolom kedua dikalikan dengan baris pertamanya. Hasil perkalian akan menjadi anggota bilangan pada baris pertama dan kolom kedua matriks.
  
  3. Matriks B's kolom ketiga dikalikan dengan baris pertamanya. Hasil perkalian akan menjadi anggota bilangan pada baris pertama dan kolom ketiga yang dihasilkan dari perkalian.
4. Kalikan baris kedua matriks A dengan kolom pertama matriks B. Anggota angka pada baris kedua dan kolom pertama hasil perkalian akan dihasilkan.
  
  5. Kalikan baris kedua matriks A dengan kolom kedua matriks B. Anggota bilangan pada baris kedua dan kolom kedua hasil perkalian akan dihasilkan.
  
  6. Kalikan baris kedua matriks A dengan kolom ketiga matriks B. Hasilnya akan menjadi anggota bilangan pada baris kedua dan kolom ketiga matriks yang dihasilkan dari perkalian.
  
  7. Kalikan baris ketiga matriks A dengan kolom pertama matriks B. Anggota angka pada baris ketiga dan kolom pertama hasil perkalian akan dihasilkan.
  
  
  8. Matriks B's kolom kedua harus dikalikan dengan baris ketiga matriks A. Hasilnya akan menjadi anggota bilangan pada baris ketiga dan kolom kedua matriks perkalian.
  
  9. Kalikan baris ketiga matriks A dengan kolom ketiga matriks B. Anggota bilangan pada baris ketiga dan kolom ketiga hasil perkalian akan dihasilkan.



  \begin{align*}
A+B&=
\begin{bmatrix}
a11&a12&a13\\
a21&a22&a23\\
a31&a32&a33\\
\end{bmatrix}
+
\begin{bmatrix}
b11&b12&b13\\
b21&b22&b23\\
b31&b32&b33\\
\end{bmatrix}\
&=
\begin{bmatrix}
a11.b11+a12.b21+a13.b31&a11.b12+a12.b22+a13.b32&a11.b11+a12.b12+a13.b12\\
a21.b11+a22.b21+a23.b31&a21.b12+a22.b22+a23.b32&a21.b21+a22.b22+a23.b33\\
a31.b11+a32.b21+a33.b31&a31.b12+a32.b22+a33.b32&a31.b31+a32.b32+a33.b33\\
\end{bmatrix}
=\begin{bmatrix}
ab11&ab12&ab13\\
ab21&ab22&ab23\\
ab31&ab32&ab33\\
\end{bmatrix}
\end{align*}



In [ ]:
#membuat struktur matriks
import numpy as np
import sympy as sy

#mendefinisikan matrik a
a=np.array([[3,7],[1,10],[3,7]])
# #operasi tranpose matriks
# ctran=a.transpose()
# ctrans=a@ctran
# print(ctrans)

# Fungsi untuk mentranspose matriks
def transpose_matriks(matriks):
    # Menghitung jumlah baris dan kolom
    baris = len(matriks)
    kolom = len(matriks[0])

    # Inisialisasi matriks hasil transpose
    transpose = []
    for j in range(kolom):
        # Baris baru untuk setiap kolom di matriks transpose
        baris_baru = []
        for i in range(baris):
            # Menambahkan elemen yang sesuai ke baris baru
            baris_baru.append(matriks[i][j])
        # Menambahkan baris baru ke matriks transpose
        transpose.append(baris_baru)

    return transpose

hasil_transpose = transpose_matriks(a)

print("Matriks Awal:")
for row in a:
  print(row)

print("\nHasil Transpose:")
for row in hasil_transpose:
    print(row)


Matriks Awal:
[3 7]
[ 1 10]
[3 7]

Hasil Transpose:
[3, 1, 3]
[7, 10, 7]


Transpose matriks adalah matriks baru yang dibuat dengan menukar elemen baris menjadi elemen kolom atau sebaliknya. Matriks transpose memiliki karakteristik berikut.


1. (A + B)T = (A)T + (B)T
2. (AT)T = A
3. (AB)T = (A)T (B)T
4. (kA)T = k.AT, dengan k = konstanta

Cara Mengerjakan

Cara Melakukannya

Matriks A memiliki elemen yang disusun dengan cara berikut:

baris pertama a dan b,
baris kedua c dan d,
dan baris ketiga e dan f.
Kolom pertama a, c, dan e, dan kolom kedua b, d, dan f.


Karena itu, susunan transpose matriks A adalah sebagai berikut:

baris pertama a, c, dan e;
baris kedua b, d, dan f;
kolom pertama a dan b;
kolom kedua c dan d;
dan kolom ketiga e dan f.

*teks yang dimiringkan*$$
\text{Untuk melakukan transpose pada matriks } a \text{, langkah-langkahnya adalah sebagai berikut:}
$$

$$
\text{Matriks } a :
$$

$$
a = \begin{bmatrix} a11 & a12 \\ a21 & a22 \\ a31 & a32 \end{bmatrix}
$$

$$
\text{Transpose dari } a \text{, disimbolkan dengan } a^T \text{, akan mengubah baris menjadi kolom dan sebaliknya, sehingga:}
$$

$$
a^T = \begin{bmatrix} a11 & a21 & a31 \\ a12 & a22 & a32 \end{bmatrix}
$$

$$
\text{Ini adalah matriks hasil transpose dari matriks } a \text{. Dalam matriks hasil transpose, baris pertama dari matriks asal menjadi kolom pertama,}
$$
$$
\text{baris kedua menjadi kolom kedua, dan seterusnya.}
$$


In [ ]:
#membuat struktur matriks
import numpy as np
import sympy as sy

m=np.array([[3,1,3],[8,3,10],[2,1,3]])
#mendefinisikan matfrik a
n=np.array([[1,8,7],[1,2,5],[4,7,1]])
#mendefinisikan matrik b
k=np.array([[1,2,7],[3,5,7],[1,4,3]])
#membuat variabel a untuk menampung hasil perkalian dari matriks m dan n
# Inisialisasi matriks hasil perkalian dengan ukuran yang sesuai
a=np.array([[0,0,0],[0,0,0],[0,0,0]])
# Inisialisasi matriks hasil perkalian dengan ukuran yang sesuai
b=np.array([[0,0,0],[0,0,0],[0,0,0]])
# Inisialisasi matriks hasil perkalian dengan ukuran yang sesuai
hasil=np.array([[0,0,0],[0,0,0],[0,0,0]])
# Melakukan perkalian matriks
def matriks(matri,matrik,hasi):
  for i in range(len(matri)):
      for j in range(len(matrik[0])):
          for k in range(len(matrik)):
              hasi[i][j] += matri[i][k] * matrik[k][j]
# memanggil fungsi mengalihkan matriks mxn kemudian di masukkan ke dalam variabel matriks a
matriks(m,n,a)
# memanggil fungsi mengalihkan matriks nxk kemudian di masukkan ke dalam variabel matriks a
matriks(n,k,b)
# memanggil fungsi mengalihkan matriks axb kemudian di masukkan ke dalam variabel matriks hasil
matriks(a,b,hasil)

for baris in hasil:
    print(baris)


[1830 3987 5356]
[ 5418 11857 15804]
[1520 3332 4424]
