# Matriks Invers
## Pengertian Matriks Invers

Matriks invers adalah matriks yang ketika dikalikan dengan matriks asalnya menghasilkan matriks identitas. Diberikan matriks persegi $$A$$ dengan ordo $$ n \times n $$, maka matriks invers, dilambangkan dengan $$ A^{-1} $$, adalah matriks yang memenuhi persamaan $$ A \times A^{-1} = A^{-1} \times A = I $$, di mana \( I \) adalah matriks identitas ordo $$ n \times n $$.

Dalam konteks matematika, matriks invers memainkan peran penting dalam penyelesaian sistem persamaan linear, inversi transformasi linier, dan berbagai aplikasi lainnya. Matriks invers hanya dapat ditemukan untuk matriks persegi yang non-singular (determinannya tidak nol). Jika determinan matriks \( A \) adalah nol, maka matriks \( A \) tidak memiliki invers.

Misalkan kita memiliki matriks $A$ sebagai berikut:
$$
\ A = \begin{bmatrix} 2 & 3 \\ 1 & 4 \end{bmatrix}\
$$

Untuk menghitung determinan, kita menggunakan rumus:
$$
\text{det}(A) = (2 \times 4) - (3 \times 1) = 8 - 3 = 5
$$




Sekarang, untuk mencari invers dari matriks $A$, kita gunakan rumus:
$$
A^{-1} = \frac{1}{\text{det}(A)} \times \text{adj}(A)
$$



Di mana $\text{adj}(A)$ adalah matriks adjoin dari $A$:
$$
\text{adj}(A) = \begin{bmatrix} 4 & -3 \\ -1 & 2 \end{bmatrix}
$$

Jadi, $A^{-1}$ akan menjadi:
$$
A^{-1} = \frac{1}{5} \times \begin{bmatrix} 4 & -3 \\ -1 & 2 \end{bmatrix} = \begin{bmatrix} \frac{4}{5} & -\frac{3}{5} \\ -\frac{1}{5} & \frac{2}{5} \end{bmatrix}
$$

Ini adalah contoh matriks invers dari matriks $A$ dan nilai determinannya adalah 5.


### Sifat sifat matriks invers

Matriks invers memiliki beberapa sifat penting yang perlu dipahami. Berikut adalah beberapa sifat utama matriks invers:

1. **Unik**: Setiap matriks persegi yang tidak singular (determinannya tidak nol) memiliki satu invers yang unik. Artinya, jika sebuah matriks memiliki invers, maka inversnya adalah tunggal.

2. **Distributif**: Matriks invers memiliki sifat distributif terhadap perkalian, yaitu jika \( A \), \( B \), dan \( C \) adalah matriks persegi yang sesuai ukuran, dan \( A \) memiliki invers, maka:
   $$
   A(B + C) = AB + AC
   $$
   dan
   $$
   (B + C)A = BA + CA
   $$

3. **Asosiatif**: Matriks invers juga mematuhi sifat asosiatif terhadap perkalian, yaitu jika \( A \), \( B \), dan \( C \) adalah matriks persegi yang sesuai ukuran, dan \( A \) memiliki invers, maka:
   $$
   A(BC) = (AB)C
   $$

4. **Identitas**: Produk matriks dengan inversnya menghasilkan matriks identitas, yaitu jika \( A \) adalah matriks persegi yang sesuai ukuran dan memiliki invers, maka:
   $$
   A \cdot A^{-1} = A^{-1} \cdot A = I
   $$
   di mana \( I \) adalah matriks identitas.

5. **Transpos**: Matriks invers dari matriks transpos adalah transpos dari matriks invers, yaitu jika \( A \) adalah matriks persegi yang sesuai ukuran dan memiliki invers, maka:
   $$
   (A^T)^{-1} = (A^{-1})^T
   $$

Sifat-sifat ini sangat penting dalam penggunaan matriks invers dalam berbagai aplikasi matematika dan ilmu terkait seperti aljabar linear, pemrosesan sinyal, dan pengolahan gambar.

### Mencari invers dengan menggunakan eliminasi gaus jordan

In [ ]:
import numpy as np

def RowSwap(A, k, l):
    temp = np.copy(A[k])
    A[k] = A[l]
    A[l] = temp

def RowScale(A, k, scale):
    A[k] *= scale

def RowAdd(A, k, l, scale):
    A[l] += A[k] * scale

def inverse_matrix(A):
    m, n = A.shape
    aug_matrix = np.hstack((A, np.identity(m)))

    for i in range(m):
        pivot_row = i
        for k in range(i + 1, m):
            if abs(aug_matrix[k, i]) > abs(aug_matrix[pivot_row, i]):
                pivot_row = k

        if pivot_row != i:
            RowSwap(aug_matrix, i, pivot_row)

        RowScale(aug_matrix, i, 1 / aug_matrix[i, i])

        for j in range(m):
            if j != i:
                RowAdd(aug_matrix, i, j, -aug_matrix[j, i])

    inverse_A = aug_matrix[:, m:]

    return inverse_A

# Persamaan asli
A = np.array([
    [2, 0, 0, 0, 0, 0],
    [0, 5, 6, 0, 0, 0],
    [0, 0, 7, 0, 0, 0],
    [0, 0, 0, 8, 9, 0],
    [0, 0, 0, 0, 10, 0],
    [0, 0, 0, 0, 0, 11],
])

# Mencari matriks invers
invers_A = inverse_matrix(A)
b = np.array([0, 0, 0, 0, 0, 0])

print("Matriks Invers menggunakan Eliminasi Gauss-Jordan:\n", invers_A)
x=invers_A@b
print(x)

Matriks Invers menggunakan Eliminasi Gauss-Jordan:
 [[ 0.5         0.          0.          0.          0.          0.        ]
 [ 0.          0.2        -0.17142857  0.          0.          0.        ]
 [ 0.          0.          0.14285714  0.          0.          0.        ]
 [ 0.          0.          0.          0.125      -0.1125      0.        ]
 [ 0.          0.          0.          0.          0.1         0.        ]
 [ 0.          0.          0.          0.          0.          0.09090909]]
[0. 0. 0. 0. 0. 0.]


### solusi persamaan linier dengan matriks invers


In [ ]:
import numpy as np

# Menentukan matriks koefisien A
A = np.array([[2, 3, -1, 4, -2, 1],
              [3, 1, 2, 1, 3, 1],
              [1, 2, -3, 1, 1, 1],
              [2, -1, 2, -1, 3, -1],
              [1, 1, -1, 1, -1, 1],
              [1, 2, 3, 1, -2, 0]])

# Menentukan vektor hasil B
B = np.array([10, 12, 8, 6, 4, 2])

# Menghitung invers dari matriks koefisien A
A_inv = np.linalg.inv(A)

# Mengalikan invers dari matriks koefisien A dengan vektor hasil B
X = np.dot(A_inv, B)
print("Solusi dari sistem persamaan linear:")
print(X)


Solusi dari sistem persamaan linear:
[ 2.86580087  0.98701299 -0.53679654  0.70995671  0.96969697 -0.12987013]


# Matriks Invers
## pengertian matriks invers
### sifat sifat matriks invers
### mencari invers dengan eliminasi gaus jordan
### solusi persamaan linier dengan mmatriks invers
membuat soal persamaan linier dengan 6 variabel