# sifat det() matriks

In [5]:
import numpy as np

n_array= np.array([[1, 0], [0, 1]]) # matriks identitas
n_array8= np.array([[3, 4], [2, 1]]) # matriks identita
n_array9= np.array([[6, 8], [4, 2]]) # matriks identita
n_array10= np.array([[6, 4], [4, 1]]) # kolom sama
n_array11= np.array([[6, 8], [2, 1]]) # baris sama
n_array12= np.array([[4, 1], [2, 1]]) # baris sama
n_array13= np.array([[7, 5], [2, 1]]) # baris sama
n_array16= np.array([[2, 1], [1, 1]]) # baris sama
n_array17= np.array([[1, 1], [1, 1]]) # baris sama
n_array18= np.array([[3, 2], [3, 2]]) # baris sama
n_array2= np.array([[1, 0,0], [0, 1, 0], [0, 0, 1]]) #matriks identitas
n_array3= np.array([[1, 2, 1], [3, 1, 2], [2, 1, 2]])
n_array5= np.array([[1, 2, 1], [2, 4, 2], [2, 1, 2]]) # matriks dengan baris yang merupakan kelipatan dari baris laiinya
n_array6= np.array([[1, 2, 1], [2, 4, 2], [2, 4, 3]]) # matriks dengan kolom yang merupakan kelipatan dari kolom laiinya
n_array4= np.array([[1, 2, 1], [2, 1, 2], [3, 1, 2]]) # merubah baris 2 dengan 3
n_array7= np.array([[6, 2, 4], [2, 4, 2], [4, 2, 4]]) # merubah baris 2 dengan 3
n_array14= np.array([[1, 3, 2], [0, 2, 2], [0, 0, 1]]) # merubah baris 2 dengan 3
n_array15= np.array([[1, 0, 0], [1, 2, 0], [1, 2, 1]]) # merubah baris 2 dengan 3

# Displaying the Matrix
print("Numpy Matrix is:")
print(n_array)
print(n_array2)
print(n_array3)
print(n_array4)
print(n_array5)
print(n_array6)
print(n_array7)
print(n_array8)
print(n_array9)
print(n_array10)
print(n_array11)
print(n_array12)
print(n_array13)
print(n_array13)
print(n_array14)
print(n_array15)
print(n_array16)
print(n_array17)
print(n_array18)
# calculating the determinant of matrix
det = np.linalg.det(n_array)
det2 = np.linalg.det(n_array2)
det3 = np.linalg.det(n_array3)
det4 = np.linalg.det(n_array4)
det5 = np.linalg.det(n_array5)
det6 = np.linalg.det(n_array6)
det7 = np.linalg.det(n_array7)
det8 = np.linalg.det(n_array8)
det9 = np.linalg.det(n_array9)
det10 = np.linalg.det(n_array10)
det11 = np.linalg.det(n_array11)
det12 = np.linalg.det(n_array12)
det13 = np.linalg.det(n_array13)
det14 = np.linalg.det(n_array14)
det15 = np.linalg.det(n_array15)
det16 = np.linalg.det(n_array16)
det17 = np.linalg.det(n_array17)
det18 = np.linalg.det(n_array18)
print("\nDeterminant of given 2X2 matrix:")
# maatriks identitas dengan hasil determinannya adalah 1
print(int(det))
print(int(det2))
# matriks C
print(int(det3))
# matriks c dengan merubah baris akan mengubah tanda dari determinan
print(int(det4))
# jika suatu baris matrik adalah kelipatan dari baris laiinya maka hasilnya 0
print(int(det5))
# jika suatu kolom matrik adalah kelipatan dari kolom laiinya maka hasilnya 0
print(int(det6))
print(int(det7))
# jika suatu matrik merupakan kelipatan dari matris lainnya maka determinand dari matrik tersebut adalah kelipatan pangkat ordo dari matrik tersebut dan di kalihkan dengan hasil determinand matrik kelipatannya
print(int(det8))
print(int(det9))
# jika suatu baris matrik merupakan keliapatan dari suatu baris mmatriks makan determinad dari suatu matriks adalah kelipatan dari matriks tersebut
print(int(det10))
print(int(det11))
print(int(det12))
# jika suatu matris merupakan penjumlahan dari 2 matriks maka hasilnya akan di jumlahkan
print(det13)
# jika suatu matriks membentuk segitiga atas dengan 0 di atas diagonal atas atau bawah maka determinandnya hasil perkalian diagonalnya
print(det14)
print(det15)
# jika dua matriks dikalikan maka hasil determinand dari matrik tersebut adalah hasil perkalian dari determinad matrik tersebut
print(det16)
print(det17)
print(det18)


Numpy Matrix is:
[[1 0]
 [0 1]]
[[1 0 0]
 [0 1 0]
 [0 0 1]]
[[1 2 1]
 [3 1 2]
 [2 1 2]]
[[1 2 1]
 [2 1 2]
 [3 1 2]]
[[1 2 1]
 [2 4 2]
 [2 1 2]]
[[1 2 1]
 [2 4 2]
 [2 4 3]]
[[6 2 4]
 [2 4 2]
 [4 2 4]]
[[3 4]
 [2 1]]
[[6 8]
 [4 2]]
[[6 4]
 [4 1]]
[[6 8]
 [2 1]]
[[4 1]
 [2 1]]
[[7 5]
 [2 1]]
[[7 5]
 [2 1]]
[[1 3 2]
 [0 2 2]
 [0 0 1]]
[[1 0 0]
 [1 2 0]
 [1 2 1]]
[[2 1]
 [1 1]]
[[1 1]
 [1 1]]
[[3 2]
 [3 2]]

Determinant of given 2X2 matrix:
1
1
-3
3
0
0
24
-5
-19
-9
-9
2
-2.9999999999999982
2.0
2.0
1.0
0.0
0.0
