# sifat det() matriks

In [3]:
import numpy as np

n_array= np.array([[1, 0], [0, 1]]) # matriks identitas
n_array8= np.array([[3, 4], [2, 1]]) # matriks identita
n_array9= np.array([[6, 8], [4, 2]]) # matriks identita
n_array10= np.array([[6, 4], [4, 1]]) # kolom sama
n_array11= np.array([[6, 8], [2, 1]]) # baris sama
n_array12= np.array([[4, 1], [2, 1]]) # baris sama
n_array13= np.array([[7, 5], [2, 1]]) # baris sama
n_array16= np.array([[2, 1], [1, 1]]) # baris sama
n_array17= np.array([[1, 1], [1, 1]]) # baris sama
n_array18= np.array([[3, 2], [3, 2]]) # baris sama
n_array2= np.array([[1, 0,0], [0, 1, 0], [0, 0, 1]]) #matriks identitas
n_array3= np.array([[1, 2, 1], [3, 1, 2], [2, 1, 2]])
n_array5= np.array([[1, 2, 1], [2, 4, 2], [2, 1, 2]]) # matriks dengan baris yang merupakan kelipatan dari baris laiinya
n_array6= np.array([[1, 2, 1], [2, 4, 2], [2, 4, 3]]) # matriks dengan kolom yang merupakan kelipatan dari kolom laiinya
n_array4= np.array([[1, 2, 1], [2, 1, 2], [3, 1, 2]]) # merubah baris 2 dengan 3
n_array7= np.array([[6, 2, 4], [2, 4, 2], [4, 2, 4]]) # merubah baris 2 dengan 3
n_array14= np.array([[1, 3, 2], [0, 2, 2], [0, 0, 1]]) # merubah baris 2 dengan 3
n_array15= np.array([[1, 0, 0], [1, 2, 0], [1, 2, 1]]) # merubah baris 2 dengan 3

# Displaying the Matrix
print("Numpy Matrix is:")
print(n_array)
print(n_array2)
print(n_array3)
print(n_array4)
print(n_array5)
print(n_array6)
print(n_array7)
print(n_array8)
print(n_array9)
print(n_array10)
print(n_array11)
print(n_array12)
print(n_array13)
print(n_array13)
print(n_array14)
print(n_array15)
print(n_array16)
print(n_array17)
print(n_array18)
# calculating the determinant of matrix
det = np.linalg.det(n_array)
det2 = np.linalg.det(n_array2)
det3 = np.linalg.det(n_array3)
det4 = np.linalg.det(n_array4)
det5 = np.linalg.det(n_array5)
det6 = np.linalg.det(n_array6)
det7 = np.linalg.det(n_array7)
det8 = np.linalg.det(n_array8)
det9 = np.linalg.det(n_array9)
det10 = np.linalg.det(n_array10)
det11 = np.linalg.det(n_array11)
det12 = np.linalg.det(n_array12)
det13 = np.linalg.det(n_array13)
det14 = np.linalg.det(n_array14)
det15 = np.linalg.det(n_array15)
det16 = np.linalg.det(n_array16)
det17 = np.linalg.det(n_array17)
det18 = np.linalg.det(n_array18)
print("\nDeterminant of given 2X2 matrix:")
# maatriks identitas dengan hasil determinannya adalah 1
print(int(det))
print(int(det2))
# matriks C
print(int(det3))
# matriks c dengan merubah baris akan mengubah tanda dari determinan
print(int(det4))
# jika suatu baris matrik adalah kelipatan dari baris laiinya maka hasilnya 0
print(int(det5))
# jika suatu kolom matrik adalah kelipatan dari kolom laiinya maka hasilnya 0
print(int(det6))
print(int(det7))
# jika suatu matrik merupakan kelipatan dari matris lainnya maka determinand dari matrik tersebut adalah kelipatan pangkat ordo dari matrik tersebut dan di kalihkan dengan hasil determinand matrik kelipatannya
print(int(det8))
print(int(det9))
# jika suatu baris matrik merupakan keliapatan dari suatu baris mmatriks makan determinad dari suatu matriks adalah kelipatan dari matriks tersebut
print(int(det10))
print(int(det11))
print(int(det12))
# jika suatu matris merupakan penjumlahan dari 2 matriks maka hasilnya akan di jumlahkan
print(det13)
# jika suatu matriks membentuk segitiga atas dengan 0 di atas diagonal atas atau bawah maka determinandnya hasil perkalian diagonalnya
print(det14)
print(det15)
# jika dua matriks dikalikan maka hasil determinand dari matrik tersebut adalah hasil perkalian dari determinad matrik tersebut
print(det16)
print(det17)
print(det18)


Numpy Matrix is:
[[1 0]
 [0 1]]
[[1 0 0]
 [0 1 0]
 [0 0 1]]
[[1 2 1]
 [3 1 2]
 [2 1 2]]
[[1 2 1]
 [2 1 2]
 [3 1 2]]
[[1 2 1]
 [2 4 2]
 [2 1 2]]
[[1 2 1]
 [2 4 2]
 [2 4 3]]
[[6 2 4]
 [2 4 2]
 [4 2 4]]
[[3 4]
 [2 1]]
[[6 8]
 [4 2]]
[[6 4]
 [4 1]]
[[6 8]
 [2 1]]
[[4 1]
 [2 1]]
[[7 5]
 [2 1]]
[[7 5]
 [2 1]]
[[1 3 2]
 [0 2 2]
 [0 0 1]]
[[1 0 0]
 [1 2 0]
 [1 2 1]]
[[2 1]
 [1 1]]
[[1 1]
 [1 1]]
[[3 2]
 [3 2]]

Determinant of given 2X2 matrix:
1
1
-3
3
0
0
24
-5
-19
-9
-9
2
-2.9999999999999982
2.0
2.0
1.0
0.0
0.0


In [ ]:
import numpy as np
n_array= np.array([[3, 1, 3], [2, 1, 2], [4, 2, 1]])
print(n_array)
a:
det = np.linalg.det(n_array)
det1 = np.linalg.inv(n_array)
print(det)
print(det1)

[[3 1 3]
 [2 1 2]
 [4 2 1]]
-2.9999999999999996
[[ 1.         -1.66666667  0.33333333]
 [-2.          3.         -0.        ]
 [ 0.          0.66666667 -0.33333333]]


## menghitung determinand matriks dan invers 5x5

matrik x dengan ordo 5x5:


\begin{align*}
X&=
\begin{bmatrix}
2&3&1&1&4\\
1&2&2&3&1\\
1&2&3&4&1\\
1&1&1&2&2\\
1&3&2&1&4
\end{bmatrix}
\end{align*}

untuk menghitung invers kita mengunakan rumus:

$$ A^{-1} = \frac{1}{\text{det}(A)} \times \text{adj}(A) $$

sedangkan

$$ \text{adj}(A)={\text({conf}(A))^T}$$

untuk

$${\text{det}(A)}=a_{i,j}*c_{i,j}+a_{i,j}*c_{i,j}+...+a_{i,j}*c_{i,j}$$

dengan

$$c_{i,j}=(-1)^{i+j}*det(a_{i,j})$$




In [7]:
x=np.array([[2,3,1,1,4],[1,2,2,3,1],[1,2,3,4,1],[1,1,1,2,2],[1,3,2,1,4]])
print("matrik X dengan")
print(x)
print("dengan invers")
print(np.linalg.inv(x))
print("dengan determinand x")
print(np.linalg.det(x))
print("pembuktian dengan rumus")
print("1/detX")
print(1/np.linalg.det(x))
# mencari setiap determinand dengan pick setiap row dari matrik x
x11=([[2,2,3,1],[2,3,4,1],[1,1,2,2],[3,2,1,4]])
x12=([[1,2,3,1],[1,3,4,1],[1,1,2,2],[1,2,1,4]])
x13=([[1,2,3,1],[1,2,4,1],[1,1,2,2],[1,3,1,4]])
x14=([[1,2,2,1],[1,2,3,1],[1,1,1,2],[1,3,2,4]])
x15=([[1,2,2,3],[1,2,3,4],[1,1,1,2],[1,3,2,1]])
x21=([[3,1,1,4],[2,3,4,1],[1,1,2,2],[3,2,1,4]])
x22=([[2,1,1,4],[1,3,4,1],[1,1,2,2],[1,2,1,4]])
x23=([[2,3,1,4],[1,2,4,1],[1,1,2,2],[1,3,1,4]])
x24=([[2,3,1,4],[1,2,3,1],[1,1,1,2],[1,3,2,4]])
x25=([[2,3,1,1],[1,2,3,4],[1,1,1,2],[1,3,2,1]])
x31=([[3,1,1,4],[2,2,3,1],[1,1,2,2],[3,2,1,4]])
x32=([[2,1,1,4],[1,2,3,1],[1,1,2,2],[1,2,1,4]])
x33=([[2,3,1,4],[1,2,3,1],[1,1,2,2],[1,3,1,4]])
x34=([[2,3,1,4],[1,2,2,1],[1,1,1,2],[1,3,2,4]])
x35=([[2,3,1,1],[1,2,2,3],[1,1,1,2],[1,3,2,1]])
x41=([[3,1,1,4],[2,2,3,1],[2,3,4,1],[3,2,1,4]])
x42=([[2,1,1,4],[1,2,3,1],[1,3,4,1],[1,2,1,4]])
x43=([[2,3,1,4],[1,2,3,1],[1,2,4,1],[1,3,1,4]])
x44=([[2,3,1,4],[1,2,2,1],[1,2,3,1],[1,3,2,4]])
x45=([[2,3,1,1],[1,2,2,3],[1,2,3,4],[1,3,2,1]])
x51=([[3,1,1,4],[2,2,3,1],[2,3,4,1],[1,1,2,2]])
x52=([[2,1,1,4],[1,2,3,1],[1,3,4,1],[1,1,2,2]])
x53=([[2,3,1,4],[1,2,3,1],[1,2,4,1],[1,1,2,2]])
x54=([[2,3,1,4],[1,2,2,1],[1,2,3,1],[1,1,1,2]])
x55=([[2,3,1,1],[1,2,2,3],[1,2,3,4],[1,1,1,2]])
# mencari determinad setiap matriks yang sudah di pick rownya
det_11 = np.linalg.det(x11)
det_12 = np.linalg.det(x12)
det_13 = np.linalg.det(x13)
det_14 = np.linalg.det(x14)
det_15 = np.linalg.det(x15)
det_21 = np.linalg.det(x21)
det_22 = np.linalg.det(x22)
det_23 = np.linalg.det(x23)
det_24 = np.linalg.det(x24)
det_25 = np.linalg.det(x25)
det_31 = np.linalg.det(x31)
det_32 = np.linalg.det(x32)
det_33 = np.linalg.det(x33)
det_34 = np.linalg.det(x34)
det_35 = np.linalg.det(x35)
det_41 = np.linalg.det(x41)
det_42 = np.linalg.det(x42)
det_43 = np.linalg.det(x43)
det_44 = np.linalg.det(x44)
det_45 = np.linalg.det(x45)
det_51 = np.linalg.det(x51)
det_52 = np.linalg.det(x52)
det_53 = np.linalg.det(x53)
det_54 = np.linalg.det(x54)
det_55 = np.linalg.det(x55)
# pick A sesuai dengan baris dan kolom yang di hapus pada confaktor
a11 = x[0][0]
a12 = x[0][1]
a13 = x[0][2]
a14 = x[0][3]
a15 = x[0][4]
a21 = x[1][0]
a22 = x[1][1]
a23 = x[1][2]
a24 = x[1][3]
a25 = x[1][4]
a31 = x[2][0]
a32 = x[2][1]
a33 = x[2][2]
a34 = x[2][3]
a35 = x[2][4]
a41 = x[3][0]
a42 = x[3][1]
a43 = x[3][2]
a44 = x[3][3]
a45 = x[3][4]
a51 = x[4][0]
a52 = x[4][1]
a53 = x[4][2]
a54 = x[4][3]
a55 = x[4][4]
# menghitung confaktor setiap baris dengan mengalihkan a dan c dan menjumlahkannya
c11 = (-1)**(1+1) * det_11
c12 = (-1)**(1+2) * det_12
c13 = (-1)**(1+3) * det_13
c14 = (-1)**(1+4) * det_14
c15 = (-1)**(1+5) * det_15
c21 = (-1)**(2+1) * det_21
c22 = (-1)**(2+2) * det_22
c23 = (-1)**(2+3) * det_23
c24 = (-1)**(2+4) * det_24
c25 = (-1)**(2+5) * det_25
c31 = (-1)**(3+1) * det_31
c32 = (-1)**(3+2) * det_32
c33 = (-1)**(3+3) * det_33
c34 = (-1)**(3+4) * det_34
c35 = (-1)**(3+5) * det_35
c41 = (-1)**(4+1) * det_41
c42 = (-1)**(4+2) * det_42
c43 = (-1)**(4+3) * det_43
c44 = (-1)**(4+4) * det_44
c45 = (-1)**(4+5) * det_45
c51 = (-1)**(5+1) * det_51
c52 = (-1)**(5+2) * det_52
c53 = (-1)**(5+3) * det_53
c54 = (-1)**(5+4) * det_54
c55 = (-1)**(5+5) * det_55

# Row 1
det_S_row1 = a11*c11 + a12*c12 + a13*c13 + a14*c14 + a15*c15
print(f"det s = {det_S_row1}")
# Row 2
det_S_row2 = a21*c21 + a22*c22 + a23*c23 + a24*c24 + a25*c25
print(f"det s = {det_S_row2}")
# Row 3
det_S_row3 = a31*c31 + a32*c32 + a33*c33 + a34*c34 + a35*c35
print(f"det s = {det_S_row3}")
# Row 4
det_S_row4 = a41*c41 + a42*c42 + a43*c43 + a44*c44 + a45*c45
print(f"det s = {det_S_row4}")
# Row 5
det_S_row5 = a51*c51 + a52*c52 + a53*c53 + a54*c54 + a55*c55
print(f"det s = {det_S_row5}")
print()
Kof_Matrix_S = np.array([[c11,c12,c13,c14,c15],[c21,c22,c23,c24,c25],[c31,c32,c33,c34,c35],[c41,c42,c43,c44,c45],[c51,c52,c53,c54,c55]])
print(f"Marix dengan anggota kofaktor-kofaktornya = \n{Kof_Matrix_S}")
print()
Trans_Kof_Matrix_S = Kof_Matrix_S.transpose()
print(f"Transpose Matrix dari kofaktornya = \n{Trans_Kof_Matrix_S}")
print()
invers_S = 1 / det_S_row1 * Trans_Kof_Matrix_S
print(f"Hasil perkalian {1/np.linalg.det(x)} dengan \n {Trans_Kof_Matrix_S } \n menghasilkanInvers Matrix adalah = \n{invers_S.round(1)}")

matrik X dengan
[[2 3 1 1 4]
 [1 2 2 3 1]
 [1 2 3 4 1]
 [1 1 1 2 2]
 [1 3 2 1 4]]
dengan invers
[[ 1.66666667 -2.5         2.16666667 -0.83333333 -1.16666667]
 [-0.33333333  2.         -1.33333333 -0.33333333  0.33333333]
 [ 0.66666667 -2.5         2.16666667 -0.83333333 -0.16666667]
 [-0.66666667  1.5        -1.16666667  0.83333333  0.16666667]
 [-0.33333333  0.         -0.33333333  0.66666667  0.33333333]]
dengan determinand x
5.999999999999997
pembuktian dengan rumus
1/detX
0.16666666666666674
det s = 6.0000000000000036
det s = 5.999999999999975
det s = 6.0
det s = 6.000000000000007
det s = 5.999999999999999

Marix dengan anggota kofaktor-kofaktornya = 
[[ 10.  -2.   4.  -4.  -2.]
 [-15.  12. -15.   9.  -0.]
 [ 13.  -8.  13.  -7.  -2.]
 [ -5.  -2.  -5.   5.   4.]
 [ -7.   2.  -1.   1.   2.]]

Transpose Matrix dari kofaktornya = 
[[ 10. -15.  13.  -5.  -7.]
 [ -2.  12.  -8.  -2.   2.]
 [  4. -15.  13.  -5.  -1.]
 [ -4.   9.  -7.   5.   1.]
 [ -2.  -0.  -2.   4.   2.]]

Hasil perkalia