#menggambar persaam bidang dalam ruang 3D
1.

#penyelesaian sistem linier
penyelesaian sistem persamaan linier meggunkan eliminasi gauss
#selesai kan persamaan berikut
$$
8x_1+9x_2+x_3=19\\
x_1+2x_2+3x_3=9\\
2x_1+x_2-x_3=5
$$

berikut penyelesaian di atas

In [ ]:
import numpy as np
#menukar list 0 dengan list 2
A=np.array([[1,2,3,9],[2,1,-1,5],[8,9,1,19]])
print(A)

[[ 1  2  3  9]
 [ 2  1 -1  5]
 [ 8  9  1 19]]


In [ ]:
def RowSwap(A,k,l):
# =============================================================================
#     A is a NumPy array.  RowSwap will return duplicate array with rows
#     k and l swapped.
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A

    B = np.copy(A).astype('float64')

    for j in range(n):
        temp = B[k][j]
        B[k][j] = B[l][j]
        B[l][j] = temp

    return B

def RowScale(A,k,scale):
# =============================================================================
#     A is a NumPy array.  RowScale will return duplicate array with the
#     entries of row k multiplied by scale.
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A

    B = np.copy(A).astype('float64')

    for j in range(n):
        B[k][j] *= scale

    return B

def RowAdd(A,k,l,scale):
# =============================================================================
#     A is a numpy array.  RowAdd will return duplicate array with row
#     l modifed.  The new values will be the old values of row l added to
#     the values of row k, multiplied by scale.
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A

    B = np.copy(A).astype('float64')

    for j in range(n):
        B[l][j] += B[k][j]*scale

    return B

In [ ]:
B1 = RowSwap(A,0,2)
B2 = RowScale(A,2,0.5)
B3 = RowAdd(A,0,1,2)

In [ ]:
## Tambahkan -1 kali baris 0 ke baris 1
A1 = RowAdd(A,0,1,-2)
print(A1,'\n')

# ## Tambahkan -4 kali baris 0 ke baris 2
A2 = RowAdd(A1,1,2,3)
print(A2,'\n')

# ## kurangi 8 pada baris ke 2
A3 = RowScale(A2,2,-8)
print(A3,'\n')

# ## Kalikan baris 1 dengan 1/3
# A4 = RowScale(A3,1,1-8
# print(A4,'\n')

# ## Kalikan baris 2 dengan 1/19
# A5 = RowScale(A4,2,1.0/-19.)
# print(A5)

[[  1.   2.   3.   9.]
 [  0.  -3.  -7. -13.]
 [  8.   9.   1.  19.]] 

[[  1.   2.   3.   9.]
 [  0.  -3.  -7. -13.]
 [  8.   0. -20. -20.]] 



TypeError: RowScale() missing 1 required positional argument: 'scale'