##aljabar matrik
 - berikan penjellasan apa itu matrik
 - operasi matrik PENJUMLAHAN PERKALIAN tranpose
 - buat program untuk menalihkah matrik a dan b m x n matriks a,n x k matriks b

saya di suruh membuat maatriks

TIDAK MENGERJAKAN DI LUAR

In [2]:
import numpy as np
import sympy as sy

a=np.array([[1,2,4],[3,2,5],[2,3,1]])
print(a)
b=np.array([[1,2,7],[9,2,5],[4,3,1]])
print(b)
c=A=np.array([[1,4],[2,5],[2,3]])
print(c)
d=np.array([[7,2,4],[3,2,8],[2,5,1]])
print(d)
e=a+b
print(e)
f=2*a
print(f)
g=a@c
print(g)
print(g.shape)
h=b@c
i=a@h
print(i)
j=a@b
k=j@c
print(k)
ctran=c.transpose()
ctrans=c@ctran
print(ctrans)

[[1 2 4]
 [3 2 5]
 [2 3 1]]
[[1 2 7]
 [9 2 5]
 [4 3 1]]
[[1 4]
 [2 5]
 [2 3]]
[[7 2 4]
 [3 2 8]
 [2 5 1]]
[[ 2  4 11]
 [12  4 10]
 [ 6  6  2]]
[[ 2  4  8]
 [ 6  4 10]
 [ 4  6  2]]
[[13 26]
 [17 37]
 [10 26]]
(3, 2)
[[113 293]
 [163 397]
 [119 287]]
[[113 293]
 [163 397]
 [119 287]]
[[17 22 14]
 [22 29 19]
 [14 19 13]]


In [3]:
#transpose
ctran=c.transpose()
ctrans=c@ctran
print(ctrans)

[[17 22 14]
 [22 29 19]
 [14 19 13]]
